# Generated by Django 5.0.9 on 2024-09-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='products_specs',
            new_name='product_specs',
        ),
    ]
