# Generated by Django 5.0.9 on 2024-09-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='content_textW',
            new_name='content_text',
        ),
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=models.BinaryField(max_length='max', null=True),
        ),
    ]
