# Generated by Django 5.0.9 on 2024-09-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0002_rename_content_textw_document_content_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
    ]
