# Generated by Django 5.0.9 on 2024-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0003_remove_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='product_specs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
